name: CI

on:
  push:
    branches: [main]
    tags:
      - "*"
  pull_request:
    branches: [main]

env:
  DOCKER_IMAGE: "royalmist/creapi"
  EARTHLY_VERSION: 0.6.15
  FORCE_COLOR: 1

jobs:
  build:
    name: Earthly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Earthly
        run: sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v${{ env.EARTHLY_VERSION}}/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'
      - name: Base
        run: earthly --ci --remote-cache=${{ env.DOCKER_IMAGE }}:base --push +base
      - name: Lint
        run: earthly --ci --remote-cache=${{ env.DOCKER_IMAGE }}:lint --push +lint
      - name: Test
        run: earthly --ci --remote-cache=${{ env.DOCKER_IMAGE }}:test --push -P +test
      - name: Build
        run: earthly --ci --remote-cache=${{ env.DOCKER_IMAGE }}:build --push +build
      - name: Nightly
        run: earthly --ci --push +docker --IMAGE=${{ env.DOCKER_IMAGE }}
      - name: Tag
        if: ${{ contains(github.ref, 'refs/tags/') }}
        id: tagName
        uses: olegtarasov/get-tag@v2.1
      - name: Release
        if: ${{ contains(github.ref, 'refs/tags/') }}
        run: earthly --ci --push +docker --IMAGE=${{ env.DOCKER_IMAGE }} --TAG=${{ steps.tagName.outputs.tag }}
